# NumPy

* Numerical Python
* Bilimsel hesaplamalar için kullanılır.
* Arraylar / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
* Temelleri 1995'te (matrix-sig, Guido Van Rossum) atılmış nihai olarak 2005(Travis Oliphant) yılında hayata geçmiştir.
* NDarrayler, listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır.

## Neden NumPy

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [6]:
a*b

array([ 2,  6, 12, 20])

## NumPy Array'i Olusturmak

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.array([3.14, 4, 2, 13])      #listede bir tane float oldugu icin hepsini floata cevirdi.

array([ 3.14,  4.  ,  2.  , 13.  ])

In [12]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [13]:
#sifirdan array olusturma

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10, dtype = int)               #tek boyutlu array (vektor)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3,5),dtype = int)              #iki boyutlu array (matris)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [18]:
np.arange(0,31,3)                                   # *

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [19]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
np.random.normal(10, 4, (3,4))                      #rastgele float sayılar  * 

array([[12.37571995,  8.48267704,  4.69653581,  9.29648243],
       [ 6.45905577, 14.18199851, 10.64497009,  8.48847832],
       [15.89210592, 16.90761139, 13.14349985, 10.05248694]])

In [21]:
np.random.randint(0,10, (3,3))                      #rastgele int sayılar    *

array([[0, 8, 2],
       [3, 1, 9],
       [3, 8, 1]])

## NumPy array Ozellikleri

* **ndim**: _boyut sayısı_
* **shape**: _boyut bilgisi_
* **size**: _toplam eleman sayısı_
* **dtype**: _array veri tipi_

In [22]:
np.random.randint(10, size = 10)

array([2, 4, 4, 9, 5, 6, 2, 2, 7, 8])

In [23]:
a = np.random.randint(10, size = 10)

In [24]:
a.ndim

1

In [25]:
a.shape

(10,)

In [26]:
a.size

10

In [27]:
a.dtype

dtype('int32')

In [28]:
b = np.random.randint(10, size = (3,5))

In [29]:
b

array([[9, 3, 2, 0, 7],
       [5, 8, 1, 6, 3],
       [3, 2, 3, 4, 3]])

In [30]:
b.ndim

2

In [31]:
b.shape

(3, 5)

In [32]:
b.size

15

In [33]:
b.dtype

dtype('int32')

## Yeniden Sekillendirme (reshaping)

In [34]:
import numpy as np

In [35]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a = np.arange(1,10)

In [38]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a.ndim

1

In [40]:
a.reshape((1,9))                           # tek boyutlu vektör den iki boyutlu matrise cevirme

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
b = a.reshape((1,9))

In [42]:
b.ndim

2

## Array Birlestirme ( Concatenation)

In [43]:
import numpy as np

In [44]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [45]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [46]:
z = np.array([7,8,9])

In [47]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
#iki boyut

In [49]:
a = np.array([[1,2,3],
              [4,5,6]])

In [50]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
np.concatenate([a,a], axis = 1)     # 0 satırları, 1 sutunları temsil eder.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [52]:
x = np.array([1,2,3,99,99,3,2,1])

In [53]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [54]:
a,b,c = np.split(x, [3,5])

In [55]:
a

array([1, 2, 3])

In [56]:
b

array([99, 99])

In [57]:
c

array([3, 2, 1])

In [58]:
#iki boyutlu

In [59]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [61]:
ust, alt = np.vsplit(m, [2])

In [62]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
sag, sol = np.hsplit(m, [2])

In [67]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [68]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (Sorting)

In [69]:
v = np.array([2,5,4,1,3])

In [70]:
v

array([2, 5, 4, 1, 3])

In [71]:
np.sort(v)                       #numpy dan cagırıldıgında veri setinin orjinal yapısını bozmuyor.

array([1, 2, 3, 4, 5])

In [72]:
v

array([2, 5, 4, 1, 3])

In [73]:
v.sort()                         #array in yapısını komple degistirdi.

In [74]:
v

array([1, 2, 3, 4, 5])

In [75]:
#iki boyutlu array siralama

In [76]:
m = np.random.normal(20,5, (3,3))

In [77]:
m

array([[18.20574824, 19.0292681 , 18.88246458],
       [22.5491279 , 30.20808728, 17.81055808],
       [16.28879408, 23.93428235, 27.62161113]])

In [78]:
np.sort(m, axis = 1)

array([[18.20574824, 18.88246458, 19.0292681 ],
       [17.81055808, 22.5491279 , 30.20808728],
       [16.28879408, 23.93428235, 27.62161113]])

In [79]:
np.sort(m, axis = 0)

array([[16.28879408, 19.0292681 , 17.81055808],
       [18.20574824, 23.93428235, 18.88246458],
       [22.5491279 , 30.20808728, 27.62161113]])

## Index ile Elemanlara Erismek

In [80]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([2, 9, 8, 1, 1, 8, 0, 6, 2, 2])

In [81]:
a[0]

2

In [82]:
a[-1]

2

In [83]:
a[0] = 100

In [84]:
a

array([100,   9,   8,   1,   1,   8,   0,   6,   2,   2])

In [85]:
m = np.random.randint(10, size = (3,5))
m

array([[3, 4, 4, 9, 8],
       [1, 4, 0, 3, 8],
       [8, 0, 3, 7, 8]])

In [86]:
m[0,0]

3

In [87]:
m[1,1]

4

In [88]:
m[1,4]

8

In [89]:
m[1,4] = 99

In [90]:
m

array([[ 3,  4,  4,  9,  8],
       [ 1,  4,  0,  3, 99],
       [ 8,  0,  3,  7,  8]])

In [91]:
m[1,4] = 2.2                   #ondalıklı kısmını eklemez, ondalıklı kısmını siler ekler.

In [92]:
m

array([[3, 4, 4, 9, 8],
       [1, 4, 0, 3, 2],
       [8, 0, 3, 7, 8]])

## Slicing ile Elemanlara Erismek (Array Alt Kumesine Erismek)

In [93]:
a = np.arange(20,30)

In [94]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [95]:
a[0:3]

array([20, 21, 22])

In [96]:
a[:3]

array([20, 21, 22])

In [97]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [98]:
a[1::2]

array([21, 23, 25, 27, 29])

In [99]:
a[0::3]

array([20, 23, 26, 29])

In [100]:
#iki boyutlu slice islemleri

In [101]:
m = np.random.randint(10, size = (5,5))
m

array([[6, 9, 3, 4, 0],
       [0, 0, 1, 0, 9],
       [2, 1, 7, 7, 3],
       [7, 5, 8, 8, 7],
       [7, 6, 6, 4, 8]])

In [102]:
m[:,0]

array([6, 0, 2, 7, 7])

In [103]:
m[:,1]

array([9, 0, 1, 5, 6])

In [104]:
m[:,4]

array([0, 9, 3, 7, 8])

In [105]:
m[0,:]

array([6, 9, 3, 4, 0])

In [106]:
m[1,:]

array([0, 0, 1, 0, 9])

In [107]:
m[0:2, 0:3]

array([[6, 9, 3],
       [0, 0, 1]])

In [108]:
m[:,0:2]

array([[6, 9],
       [0, 0],
       [2, 1],
       [7, 5],
       [7, 6]])

In [109]:
m[1:3, 0:2]

array([[0, 0],
       [2, 1]])

## Alt Kume Uzerinde Islem Yapmak

In [110]:
a = np.random.randint(10, size = (5,5))
a

array([[4, 3, 5, 6, 3],
       [4, 7, 3, 4, 7],
       [8, 6, 1, 5, 8],
       [9, 2, 5, 6, 0],
       [2, 8, 8, 0, 9]])

In [111]:
alt_a = a[0:3, 0:2]
alt_a

array([[4, 3],
       [4, 7],
       [8, 6]])

In [112]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [113]:
alt_a

array([[99999,     3],
       [    4,   888],
       [    8,     6]])

In [114]:
a

array([[99999,     3,     5,     6,     3],
       [    4,   888,     3,     4,     7],
       [    8,     6,     1,     5,     8],
       [    9,     2,     5,     6,     0],
       [    2,     8,     8,     0,     9]])

In [121]:
m = np.random.randint(10, size = (5,5))
m

array([[9, 2, 3, 7, 9],
       [6, 9, 7, 2, 2],
       [7, 5, 5, 2, 2],
       [1, 3, 4, 4, 5],
       [6, 4, 3, 6, 7]])

In [122]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[9, 2],
       [6, 9],
       [7, 5]])

In [123]:
alt_b[0,0] = 9999

In [124]:
alt_b

array([[9999,    2],
       [   6,    9],
       [   7,    5]])

In [125]:
m

array([[9, 2, 3, 7, 9],
       [6, 9, 7, 2, 2],
       [7, 5, 5, 2, 2],
       [1, 3, 4, 4, 5],
       [6, 4, 3, 6, 7]])

## Fancy Index ile Elemanlara Erismek

In [126]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [127]:
v[1]

3

In [128]:
v[3]

9

In [129]:
v[5]

15

In [132]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [133]:
al_getir = [1,3,5]

In [134]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [135]:
v[al_getir]

array([ 3,  9, 15])

In [136]:
#iki boyutta fancy

In [137]:
m = np.arange(9).reshape((3,3))

In [138]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [139]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [140]:
m[satir, sutun]

array([1, 5])

In [144]:
#basit index ile fancy index

In [145]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [146]:
m[0, [1,2]]

array([1, 2])

In [149]:
#slice ile fancy

In [150]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Kosullu Eleman Islemleri

In [151]:
v = np.array([1,2,3,4,5])

In [152]:
v < 3

array([ True,  True, False, False, False])

In [153]:
v[v < 3]

array([1, 2])

In [154]:
v[v > 3]

array([4, 5])

In [156]:
v[v >= 3]

array([3, 4, 5])

In [157]:
v[v <= 3]

array([1, 2, 3])

In [158]:
v[v == 3]

array([3])

In [159]:
v[v != 3]

array([1, 2, 4, 5])

In [160]:
v

array([1, 2, 3, 4, 5])

In [161]:
v * 2

array([ 2,  4,  6,  8, 10])

In [162]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [163]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [165]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

## Matematiksel Islemler

In [166]:
v = np.array([1,2,3,4,5])

In [167]:
v - 1

array([0, 1, 2, 3, 4])

In [168]:
v * 5

array([ 5, 10, 15, 20, 25])

In [169]:
v * 5 /10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [170]:
#ufunc

In [173]:
np.subtract(v, 1)                  #her bir elemandan 1 çıkar.

array([0, 1, 2, 3, 4])

In [175]:
np.add(v, 1)                       #her bir elemana bir ekle.

array([2, 3, 4, 5, 6])

In [176]:
np.multiply(v, 4)                  #her bir elemanı 4 ile çarp.

array([ 4,  8, 12, 16, 20])

In [179]:
np.divide(v, 3)                    #her bir elemanı 3 e bol.

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [180]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [181]:
np.power(v, 3)                     #her bir elemanın kupunu alıyor.

array([  1,   8,  27,  64, 125], dtype=int32)

In [182]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [184]:
np.mod(v, 2)                       #mod alma

array([1, 0, 1, 0, 1], dtype=int32)

In [186]:
np.absolute(np.array([-3]))        #mutlak degerini alma

array([3])

In [188]:
np.sin(360)                        #trigonometri hesaplama

0.9589157234143065

In [189]:
np.cos(180)

-0.5984600690578581

In [190]:
v = np.array([1,2,3])

In [191]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [192]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [193]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [194]:
?np

In [195]:
#cheatsheet                        #numpy mathematics cheat sheet     -google da arat. ipucu

## Istatistiksel Hesaplamalar

* np.mean(arr,axis=0) | Returns mean along specific axis
* arr.sum() | Returns sum of arr
* arr.min() | Returns minimum value of arr
* arr.max(axis=0) | Returns maximum value of specific axis
* np.var(arr) | Returns the variance of array
* np.std(arr,axis=1) | Returns the standard deviation of specific axis
* arr.corrcoef() | Returns correlation coefficient of array

In [204]:
v

array([1, 2, 3])

In [205]:
np.mean(v)

2.0

In [206]:
v.sum()

6

In [207]:
v.min()

1

In [208]:
v.max()

3

## NumPy ile iki Bilinmeyenli Denklem Cozumu

In [214]:
a = np.array([[5,1], [1,3]])                       #bilinmeyen ifadelerin katsayılarını bir vektore koymak
b = np.array([12,10])                              #denklemin degerlerini bir vektore koymak
                                                   #ve solve isimli fonksiyonu kullanarak bunları cozmek

In [215]:
a

array([[5, 1],
       [1, 3]])

In [216]:
b

array([12, 10])

In [217]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])