## PANDAS

* Panel Data
* Veri manipulasyonu ve veri analizi icin yazılmıs acık kaynak kodlu bir Python kutuphanesidir.
* Ekonometrik ve finansal calısmalar icin dogmustur.
* Temeli 2008 yılında atılmıstır.
* R icinde DataFrame yapısını Python dunyasına tasımıs ve DataFrame'ler uzerinde hızlı ve etkili calısabilme imkanı  
  saglamıştır.
* Bir cok farklı veri tipini okuma ve yazma imkanı saglar.

## Pandas Serisi Olusturmak

In [885]:
import pandas as pd

In [886]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [887]:
seri = pd.Series([10,88,3,4,5])

In [888]:
type(seri)

pandas.core.series.Series

In [889]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [890]:
seri.dtype

dtype('int64')

In [891]:
seri.size

5

In [892]:
seri.ndim

1

In [893]:
seri.shape

(5,)

In [894]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [895]:
seri.head(3)                  #ilk 5 harfi istiyor

0    10
1    88
2     3
dtype: int64

In [896]:
seri.tail(3)                  #sondan bakmaya yarıyor

2    3
3    4
4    5
dtype: int64

In [897]:
#index isimlendirmesi

In [898]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [899]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [900]:
pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [901]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [902]:
seri["a"]

99

In [903]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [904]:
#sozluk uzerinden liste olusturmak

In [905]:
sozluk = pd.Series({"reg":10, "log":11, "cart":12})

In [906]:
sozluk

reg     10
log     11
cart    12
dtype: int64

In [907]:
sozluk = {"reg":10, "log":11, "cart":12}

In [908]:
seri = pd.Series(sozluk)

In [909]:
seri

reg     10
log     11
cart    12
dtype: int64

In [910]:
#iki seriyi birlestirerek seri olusturma

In [911]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

## Eleman Islemleri

In [912]:
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [913]:
seri[0]

1

In [914]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [915]:
seri = pd.Series([121,200,150,99], index= ["reg","loj","cart","rf"])

In [916]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [917]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [918]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [919]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [920]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [921]:
#eleman sorgulama

In [922]:
"reg" in seri

True

In [923]:
"a" in seri

False

In [924]:
seri["reg"]

121

In [925]:
#fancy eleman

In [926]:
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [927]:
seri["reg"] = 130

In [928]:
seri["reg"]

130

In [929]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

## Pandas DataFrame Olusturma

In [930]:
l = [1,2,39,67,90]

In [931]:
l

[1, 2, 39, 67, 90]

In [932]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [933]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [934]:
pd.DataFrame(m, columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [935]:
#df isimlendirme

In [936]:
df = pd.DataFrame(m, columns =  ["var1", "var2", "var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [937]:
df.columns = ["deg1","deg2","deg3"]

In [938]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [939]:
type(df)

pandas.core.frame.DataFrame

In [940]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [941]:
df.shape

(3, 3)

In [942]:
df.ndim

2

In [943]:
df.size

9

In [944]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [945]:
type(df.values)

numpy.ndarray

In [946]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [947]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [948]:
a = np.array([1,2,3,4,5])

In [949]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

## DataFrame eleman islemleri

In [950]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [951]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [952]:
sozluk

{'var1': array([7, 3, 0, 6, 1]),
 'var2': array([2, 4, 1, 7, 8]),
 'var3': array([7, 3, 1, 7, 8])}

In [953]:
df = pd.DataFrame(sozluk)

In [954]:
df

var1  var2  var3
0     7     2     7
1     3     4     3
2     0     1     1
3     6     7     7
4     1     8     8

In [955]:
df[0:1]

var1  var2  var3
0     7     2     7

In [956]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [957]:
df.index = ["a","b","c","d","e"]

In [958]:
df

var1  var2  var3
a     7     2     7
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

In [959]:
df["c":"e"]

var1  var2  var3
c     0     1     1
d     6     7     7
e     1     8     8

In [960]:
#silme

In [961]:
df.drop("a", axis = 0)

var1  var2  var3
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

In [962]:
df

var1  var2  var3
a     7     2     7
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

In [963]:
df.drop("a", axis = 0, inplace = True)     #insplace: kalıcı bir sekilde siliyor.

In [964]:
df

var1  var2  var3
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

In [965]:
#fancy

In [966]:
l = ["c","e"]

In [967]:
df.drop(l, axis = 0)

var1  var2  var3
b     3     4     3
d     6     7     7

In [968]:
#degiskenler icin

In [969]:
df

var1  var2  var3
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

In [970]:
"var1" in df

True

In [971]:
l = ["var1","var4","var2"]

In [972]:
for i in l:
    print(i in df)

True
False
True


In [973]:
df

var1  var2  var3
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

In [974]:
df["var1"]

b    3
c    0
d    6
e    1
Name: var1, dtype: int32

In [975]:
df["var4"] = df["var1"] / df["var2"]

In [976]:
df

var1  var2  var3      var4
b     3     4     3  0.750000
c     0     1     1  0.000000
d     6     7     7  0.857143
e     1     8     8  0.125000

In [977]:
df.drop("var4", axis = 1)

var1  var2  var3
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

In [978]:
df

var1  var2  var3      var4
b     3     4     3  0.750000
c     0     1     1  0.000000
d     6     7     7  0.857143
e     1     8     8  0.125000

In [979]:
df.drop("var4", axis = 1, inplace = True)

In [980]:
df

var1  var2  var3
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

In [981]:
l = ["var1","var2"]

In [982]:
df.drop(l, axis = 1)

var3
b     3
c     1
d     7
e     8

In [983]:
df

var1  var2  var3
b     3     4     3
c     0     1     1
d     6     7     7
e     1     8     8

# Gözlem Ve Degisken Secimi: loc & iloc

In [984]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])


In [985]:
df

var1  var2  var3
0    10    24     6
1    29    16    28
2    19     5    15
3    23    25    22
4     7    28    27
5    14    16    29
6    25     2    23
7    26     3     9
8    23    29    25
9    19    18    23

In [986]:
?np.random.randint

In [987]:
#loc: tanımlandıgı sekli ile secim yapmak icin kullanılır.

In [988]:
df.loc[0:3]

var1  var2  var3
0    10    24     6
1    29    16    28
2    19     5    15
3    23    25    22

In [989]:
#iloc: alısık oldugumuz indeksleme mantıgı ile secim yapar.

In [990]:
df.iloc[0:3]

var1  var2  var3
0    10    24     6
1    29    16    28
2    19     5    15

In [991]:
df.iloc[0,0]

10

In [992]:
df

var1  var2  var3
0    10    24     6
1    29    16    28
2    19     5    15
3    23    25    22
4     7    28    27
5    14    16    29
6    25     2    23
7    26     3     9
8    23    29    25
9    19    18    23

In [993]:
df.iloc[:3,:2]

var1  var2
0    10    24
1    29    16
2    19     5

In [994]:
df.loc[0:3, "var3"]

0     6
1    28
2    15
3    22
Name: var3, dtype: int32

In [995]:
df.iloc[0:3]["var3"]

0     6
1    28
2    15
Name: var3, dtype: int32

## Kosullu Eleman Islemleri

In [996]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0     9    28    28
1    16    23    18
2    23     8    24
3    20    12    16
4    18    28     2
5    26    13    29
6    21    10     6
7    19    14    26
8    19    28     2
9    20     5     4

In [997]:
df["var1"]

0     9
1    16
2    23
3    20
4    18
5    26
6    21
7    19
8    19
9    20
Name: var1, dtype: int32

In [998]:
df["var1"][0:2]

0     9
1    16
Name: var1, dtype: int32

In [999]:
df[df.var1 > 15]

var1  var2  var3
1    16    23    18
2    23     8    24
3    20    12    16
4    18    28     2
5    26    13    29
6    21    10     6
7    19    14    26
8    19    28     2
9    20     5     4

In [1000]:
df[(df.var1 > 20) & (df.var3 < 15)]

var1  var2  var3
6    21    10     6

In [1001]:
df.loc[(df.var1 > 20), ["var1","var2"]]

var1  var2
2    23     8
5    26    13
6    21    10

In [1002]:
df[(df.var1 > 10)][["var1","var2"]]

var1  var2
1    16    23
2    23     8
3    20    12
4    18    28
5    26    13
6    21    10
7    19    14
8    19    28
9    20     5

# Birlestirme (Join) Islemleri

In [1003]:
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    27    19    14
1    14    29     7
2    21     2    13
3    25     2    24
4    14     2    20

In [1004]:
df2 = df1 + 99
df2

var1  var2  var3
0   126   118   113
1   113   128   106
2   120   101   112
3   124   101   123
4   113   101   119

In [1005]:
pd.concat([df1, df2])

var1  var2  var3
0    27    19    14
1    14    29     7
2    21     2    13
3    25     2    24
4    14     2    20
0   126   118   113
1   113   128   106
2   120   101   112
3   124   101   123
4   113   101   119

In [1006]:
?pd.concat

In [1007]:
pd.concat([df1,df2], ignore_index = True)     #index problemi ortadan kalktı.

var1  var2  var3
0    27    19    14
1    14    29     7
2    21     2    13
3    25     2    24
4    14     2    20
5   126   118   113
6   113   128   106
7   120   101   112
8   124   101   123
9   113   101   119

# ileri Birlestirme Islemleri

In [1008]:
df1 = pd.DataFrame({'calisanlar': ['Ali','Veli','Ayse','Fatma'],
                  'grup': ['Muhasebe','Muhendislik','Muhendislik','IK']})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [1009]:
df2 = pd.DataFrame({'calisanlar': ['Ayse','Ali','Veli','Fatma'],
                   'ilk_giris': [2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [1010]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [1011]:
#coktan teke

In [1012]:
df3 = pd.merge(df1,df2)

In [1013]:
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [1014]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'IK'],
                   'mudur': ['Caner', 'Mustafa', 'Berkcan']})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           IK  Berkcan

In [1015]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           IK       2019  Berkcan

In [1016]:
#coktan coka

In [1017]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe', 'Muhendislik', 'Muhendislik', 'IK', 'IK'],
                    'yetenekler': ['matematik', 'excel','kodlama','linux','excel','yonetim']})
df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           IK      excel
5           IK    yonetim

In [1018]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [1019]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           IK      excel
7      Fatma           IK    yonetim

# Toplulastırma ve Gruplama (Aggregation&Grouping)

Basit toplulastırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()


In [1020]:
import seaborn as sns

In [1021]:
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [1022]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [1023]:
df.shape

(1035, 6)

In [1024]:
df.mean()                            #butun degiskenlerin ortalama degerini verdi.

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [1025]:
df["mass"].mean()

2.6381605847953216

In [1026]:
df["mass"].count()

513

In [1027]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

# Gruplama Islemleri

In [1028]:
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                  'veri': [10,11,52,23,43,55]}, columns = ['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [1029]:
df.groupby("gruplar")

In [1030]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [1031]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [1032]:
df.groupby("method")

In [1033]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

# ileri Toplulastırma Islemleri (Aggregate, filter, transform, apply)

In [1034]:
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                 'degisken1': [10,23,33,22,11,99],
                 'degisken2': [100,253,333,262,111,969]},
                columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [1035]:
#aggregate

In [1036]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A               16        181
B               17        182
C               66        651

In [1037]:
df.groupby("gruplar").aggregate(["min", np.median, "max"])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10     16  22       100    181  262
B              11     17  23       111    182  253
C              33     66  99       333    651  969

In [1038]:
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                 'degisken1': [10,23,33,22,11,99],
                 'degisken': [100,253,333,262,111,969]},
                columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1 degisken2
0       A         10       NaN
1       B         23       NaN
2       C         33       NaN
3       A         22       NaN
4       B         11       NaN
5       C         99       NaN

In [1039]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [1040]:
df.groupby("gruplar").std()

degisken1
gruplar           
A         8.485281
B         8.485281
C        46.669048

In [1041]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1 degisken2
2       C         33       NaN
5       C         99       NaN